kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "alerts-group"
  auto_offset_reset: "earliest"
  enable_auto_commit: true
  client_id: "blacklist-generator"
  auto_commit_interval_ms: 5000
  producer_topic: "blacklist-events"
  consumer_topic: 
    - "blacklist-events"
  compression_type: "lz4"
  acks: "all"
redis:
  bootstrap_servers:
    - "localhost:7001"
    - "localhost:7002"
    - "localhost:7003"
    - "localhost:7004"
    - "localhost:7005"
    - "localhost:7006"
  ttl: 3600

alerts_generator:
  num_alerts: 100000
  num_ip_addresses: 10
  alert_interarrival_ms: 10