kafka:
  bootstrap_servers: "kafka:29092"
  group_id: "alerts-group"
  auto_offset_reset: "latest"
  enable_auto_commit: true
  enable_idempotence: true
  client_id: "blacklist-generator"
  auto_commit_interval_ms: 5000
  producer_topic: "blacklist-events"
  consumer_topic: 
    - "blacklist-events"
  compression_type: "lz4"
  acks: "all"
redis:
  bootstrap_servers:
    - "redis-1:7001"
    - "redis-2:7002"
    - "redis-3:7003"
    - "redis-4:7004"
    - "redis-5:7005"
    - "redis-6:7006"
  ttl: 3600
  dedup_ttl: 3600

alerts_generator:
  num_alerts: 10
  num_ip_addresses: 10
  alert_interarrival_ms: 10

clickhouse:
  user: "test"
  password: "password"
  port: 8123
  host: "clickhouse1"
