services:
  redis-1:
    image: redis:8.2-m01-alpine
    container_name: redis-1
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7001'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7001'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-1:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-2:
    image: redis:8.2-m01-alpine
    container_name: redis-node-2
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7002'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7002'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-2:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-3:
    image: redis:8.2-m01-alpine
    container_name: redis-node-3
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7003'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7003'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-3:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-4:
    image: redis:8.2-m01-alpine
    container_name: redis-node-4
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7004'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7004'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-4:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-5:
    image: redis:8.2-m01-alpine
    container_name: redis-node-5
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7005'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7005'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-5:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-6:
    image: redis:8.2-m01-alpine
    container_name: redis-node-6
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --port
      - '7006'
    healthcheck:
      interval: 10s
      retries: 3
      test:
        - CMD
        - redis-cli
        - -p
        - '7006'
        - ping
      timeout: 5s
    network_mode: host
    volumes:
      - redis-data-6:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-cluster-creator:
    image: redis:8.2-m01-alpine
    container_name: redis-cluster-creator
    command:
      - redis-cli
      - --cluster
      - create
      - localhost:7001
      - localhost:7002
      - localhost:7003
      - localhost:7004
      - localhost:7005
      - localhost:7006
      - --cluster-yes
      - --cluster-replicas
      - '1'
    depends_on:
      redis-1:
        condition: service_healthy
      redis-node-2:
        condition: service_healthy
      redis-node-3:
        condition: service_healthy
      redis-node-4:
        condition: service_healthy
      redis-node-5:
        condition: service_healthy
      redis-node-6:
        condition: service_healthy
    network_mode: host
    restart: "no"

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6: